-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 12:46:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Driver` (
  `DriverID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `AddressStreet` VARCHAR(45) NOT NULL,
  `AddressSuburb` VARCHAR(45) NOT NULL,
  `AddressPostcode` CHAR(4) NOT NULL,
  `PhoneNumber` VARCHAR(12) NULL,
  PRIMARY KEY (`DriverID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Route` (
  `RouteNumber` INT NOT NULL,
  `AveragePassengers` DECIMAL(6,1) NOT NULL,
  PRIMARY KEY (`RouteNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stage` (
  `RouteNumber` INT NOT NULL,
  `StageNumber` INT NOT NULL,
  PRIMARY KEY (`RouteNumber`, `StageNumber`),
  CONSTRAINT `fk_Stage_Route1`
    FOREIGN KEY (`RouteNumber`)
    REFERENCES `Route` (`RouteNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DriverAllocatedToStage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverAllocatedToStage` (
  `DriverID` INT NOT NULL,
  `RouteNumber` INT NOT NULL,
  `StageNumber` INT NOT NULL,
  PRIMARY KEY (`DriverID`, `RouteNumber`, `StageNumber`),
  INDEX `fk_DriverAllocatedToStage_Stage1_idx` (`RouteNumber` ASC) VISIBLE,
  CONSTRAINT `fk_DriverAllocatedToStage_Driver`
    FOREIGN KEY (`DriverID`)
    REFERENCES `Driver` (`DriverID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DriverAllocatedToStage_Stage1`
    FOREIGN KEY (`RouteNumber`)
    REFERENCES `Stage` (`RouteNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DriverTrainingCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverTrainingCourses` (
  `DriverID` INT NOT NULL,
  `TrainingCourseName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DriverID`, `TrainingCourseName`),
  CONSTRAINT `fk_DriverTrainingCourses_Driver1`
    FOREIGN KEY (`DriverID`)
    REFERENCES `Driver` (`DriverID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Town`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Town` (
  `TownID` INT NOT NULL,
  `TownName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TownID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StagePassesThroughTown`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StagePassesThroughTown` (
  `TownID` INT NOT NULL,
  `RouteNumber` INT NOT NULL,
  `StageNumber` INT NOT NULL,
  PRIMARY KEY (`TownID`, `RouteNumber`, `StageNumber`),
  INDEX `fk_StagePassesThroughTown_Stage1_idx` (`StageNumber` ASC, `RouteNumber` ASC) VISIBLE,
  CONSTRAINT `fk_StagePassesThroughTown_Stage1`
    FOREIGN KEY (`StageNumber` , `RouteNumber`)
    REFERENCES `Stage` (`StageNumber` , `RouteNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StagePassesThroughTown_Town1`
    FOREIGN KEY (`TownID`)
    REFERENCES `Town` (`TownID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Depot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Depot` (
  `DepotID` INT NOT NULL,
  `AddressStreet` VARCHAR(45) NOT NULL,
  `AddressSuburb` VARCHAR(45) NOT NULL,
  `AddressPostcode` CHAR(4) NOT NULL,
  `TownID` INT NOT NULL,
  PRIMARY KEY (`DepotID`),
  INDEX `fk_Depot_Town1_idx` (`TownID` ASC) VISIBLE,
  CONSTRAINT `fk_Depot_Town1`
    FOREIGN KEY (`TownID`)
    REFERENCES `Town` (`TownID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bus` (
  `RegistrationNumber` INT NOT NULL,
  `PassengerCapacity` INT NOT NULL,
  `Deck` INT NOT NULL,
  `RouteNumber` INT NULL,
  `DepotID` INT NOT NULL,
  PRIMARY KEY (`RegistrationNumber`),
  INDEX `fk_Bus_Depot1_idx` (`DepotID` ASC) VISIBLE,
  INDEX `fk_Bus_Route1_idx` (`RouteNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Bus_Depot1`
    FOREIGN KEY (`DepotID`)
    REFERENCES `Depot` (`DepotID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bus_Route1`
    FOREIGN KEY (`RouteNumber`)
    REFERENCES `Route` (`RouteNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
